### ISSUE TITLE
No known location for the IPT or Darwin Core

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/cmnh-izc#1]
Emailed Erika Tucker to see where the IPT or Darwin Core is located

**Comment by jhpoelen** [comment]
@EMTuckerLab see attached SCAN profile for Carnegie Museum of Natural History invertebrate zoology collection - 

https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=300

it appears that meta data is available, but not records.

![Screenshot from 2022-10-05 16-12-08](https://user-images.githubusercontent.com/1084872/194164803-ec04bfc9-4668-4271-82f3-d9044f4bd648.png)

**Comment by jhpoelen** [comment]
also, on neon biorepo, only meta-data appears to be published:

https://biokic4.rc.asu.edu/biorepo/collections/misc/collprofiles.php?collid=82

![image](https://user-images.githubusercontent.com/1084872/194165179-f2c4683b-97e9-4ef5-95bd-81f19dbe453d.png)

**Comment by jhpoelen** [comment]
work on transcribing Carnegie's parasite tracker datasets is ongoing, please see email thread below.

-----
Yes, feel free to copy the discussion to GitHub.

I still haven't uploaded the updated flea taxonomy, since I still need to generate the parent taxon relationships. Stay tuned...

On Fri, Aug 4, 2023 at 11:14 AM Jorrit Poelen <[jhpoelen@jhpoelen.nl](mailto:jhpoelen@jhpoelen.nl)> wrote:

    Hi Valerie -

    I was just going over some parasite tracker datasets, and remembered our discussion below.

    Do you mind if I share our email thread in a publicly accessible github issue via https://github.com/globalbioticinteractions/cmnh-izc?

     This way, I can keep track of ongoing activities related to your valuable CMNH translation work.

    Hope all is well,

    -jorrit

**Comment by jhpoelen** [comment]
on 2024-09-04, I heard back from Valerie Warhol of the Carnegie Museum of Natural History. She mentioned that the flea records were ready, and that Jim Fetzner the Assistant Curator for Invertebrate Zoology.

On the same day, Jim made a first version of the DwC-A available at 

https://invertebratezoology.org/DataEntry/Uploads/DataArchives/CMNH_Flea_dwca-1.0.zip

**Comment by zygoballus** [comment]
Note that this initial Darwin Core archive is only a partial representation of our full dataset (about 2300 records out of ~18000 total). Efforts to clean up the remaining data so that it is usable are ongoing. As mentioned above, this is more than normal data cleaning, as a typical record is something like:
```
host: Rats as ? 60377 Rattus niobe ♂ + ♀
date: 12/28/1967
locality: NE NEW GUINEA: Western Highlands District. Hagen Sub-Dist. Tambul. Mur-Mur Pass. Moss Forest. 2800 + \ - m. M.N. + A.B.M.
fleas: 20 + \ - 1 ♂ 0 ♀ SV. SIM. / 1 ♂ 0 ♀ ID. I Jordan, 1937 / 0 ♂ 2 ♀ SV #42 n sp ? / 1 ♂ 0 ♀ ACN EU. EU. ; 2 ♂ 2 ♀ MSV. AN. / 17 fleas in KOH SS 2/12/1968 / 0 ♂ 1 ♀ P.I. L., 1758 / 1 ♂ 1 ♀ SV. #47 n sp ? / 1 ♂ 0 ♀ PAP. AL. / 1 ♂ 0 ♀ PAP. LUL / 1 ♂ 0 ♀ PAP. ES. Paratype / 1 ♀ PAP. LUL /

**Comment by jhpoelen** [comment]
Thanks for sharing this important detail! 

Any chance you can point to the original data? I think it'd be neat to have the original just in case we need to trace back some transcriptions.

**Comment by jhpoelen** [comment]
by the way, the notation looks pretty compact - I can see why folks wanted to use it to avoid having to have giant sheets of paper laying around.

**Comment by zygoballus** [comment]
> Any chance you can point to the original data? I think it'd be neat to have the original just in case we need to trace back some transcriptions.

Sure, I've temporarily uploaded the original data (as a CSV file) to:
https://drive.google.com/file/d/1iZHxmDUPeZTN3g8GgchWHG2pRJd9drUt/view?usp=drive_link
Please feel free to add it to the repository.

**Comment by zygoballus** [comment]
BTW, some of our dates include zeroes for missing data, e.g. "1972-00-00". This is fine according to Darwin Core, but some databases don't like it. Just wanted to warn you.

**Comment by jhpoelen** [comment]
Thanks for sharing your notes and original dataset. I've added them to the repository as you hinted:

https://github.com/globalbioticinteractions/cmnh-izc/blob/668205275612e54e0c0cbc37c14cbf149af712aa/traubdataorig.csv

**Comment by zygoballus** [comment]
@jhpoelen - What is the method for updating our data in the future? Do we just publish a new Darwin Core archive and then inform you of the location of the archive?

**Comment by jhpoelen** [comment]
@zygoballus thanks for your message.

GloBI periodically revisits (~weekly or so) and pulls in any updates from the configured location. 

You can find the configured location at: 

https://github.com/globalbioticinteractions/cmnh-izc/blob/main/globi.json

which is currently:

```json
{ 
  "format": "dwca",
  "citation": "Carnegie Invertebrate Zoology Collection",
  "url": "https://invertebratezoology.org/DataEntry/Uploads/DataArchives/CMNH_Flea_dwca-1.0.zip",
  "deprecated": false
}
```

If you'd like to update the location, please feel free to create a pull request, alternatively, if you feel comfortable being a curator for your GloBI configuration  , I can add you as a contributors/owner of https://github.com/globalbioticinteractions/cmnh-izc . 

I hope this answers your questions, and please let me know how you'd like to proceed.

**Comment by zygoballus** [comment]
@jhpoelen - Thanks!! I'll update the JSON file if we need to change the location.

**Comment by jhpoelen** [comment]
@zygoballus excellent! Please do holler if you have any questions . . . I am sure there's plenty of stuff that can be improved, and I'd be curious to hear from you what you'd improve first.
